name: release

on:
  release:
    types: [created]

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: jdx/mise-action@v4
      - run: mise run build
      - run: cd schema && mise run lint

  release:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: jdx/mise-action@v4
      - run: goreleaser release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
